#-------------------------------
# General Site Settings
title: TechBrv
logo: # You can add own logo. For example '/images/logo.png'.
description: Download Nulled Scripts, Nulled WordPress Templates Plugins, Android Mod Apks and Source Codes, Software, Ebooks, Music and Sound Effects
baseurl: "oldbracia" # The subpath of your site, e.g. /blog

#-------------------------------
# Author Settings
author:
  name: Simon P
  title: Hello 👋
  description: Without technology today, you could fail in a split second. Bu having the right tool can save you tons of headaches. Download Nulled Scripts, Nulled WordPress Templates Plugins, Android Mod Apks and Source Codes, Software, Ebooks, Music and Sound Effects  #image: '/images/kaushal.jpg'
  avatar: '/images/kaushal.jpg'

social:
- {icon: "ion-logo-twitter", label: Twitter, link: "https://twitter.com/djxpat254"}
- {icon: "ion-logo-facebook", label: Facebook, link: "https://facebook.com/djxpat254"}
#- {icon: "ion-logo-dribbble", label: Dribbble, link: "https://youtube.com"}
- {icon: "ion-logo-instagram", label: Instagram, link: "https://www.instagram.com/bio.co.ke"}
- {icon: "ion-logo-whatsapp", label: WhatsApp, link: "https://wa.me/+254798584421"}

# Example of adding a new link to the author section - {icon: "ion-logo-vimeo", label: Vimeo, link: "https://vimeo.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp: true # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp__title: Get interesting news # Add your Title
mailchimp__text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Join # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: techrahisi@gmail.com # Add your email for contact form
  description: Reach me anytime.

# NOTE
# Bracia comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # UA-201137118-2 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title:output_ext
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed
